export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS'
export const GET_CONTACT = 'GET_CONTACT'
export const ADD_CONTACT = 'ADD_CONTACT'
export const EDIT_CONTACT = 'EDIT_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'

export const FILL_CONTACT_FORM = 'FILL_CONTACT_FORM'
export const UPDATE_CONTACT_FORM = 'UPDATE_CONTACT_FORM'
export const CLEAR_CONTACT_FORM = 'CLEAR_CONTACT_FORM'

export const SET_USER_DATA = 'SET_USER_DATA'

export const GET_ADDRESS_BY_CEP = 'GET_ADDRESS_BY_CEP'